irontec/ivoz-ui

package.json, src/components/Create.tsx, src/components/Edit.tsx, src/components/List/Content/ListContentValue.tsx, src/components/List/List.tsx, src/components/withRowData.tsx, src/entities/DefaultEntityBehavior.tsx, src/router/parseRoutes.tsx, src/services/entity/EntityService.ts, src/services/form/Field/Autocomplete.tsx, src/services/form/Field/CustomComponentWrapper.tsx, src/services/form/Field/ViewFieldValue.tsx, tsconfig.json
=> Error fixing

.gitignore, README.md, hygen/README.md, hygen/lib/api/get-api-properties.js, hygen/lib/index.js, hygen/lib/merger/merger-properties.js, hygen/lib/properties/properties.js, hygen/lib/template-formatter/fmt-entity-properties.js, hygen/lib/template-formatter/fmt-properties.js, hygen/templates/entity/new/Entity.ejs.t, hygen/templates/entity/new/EntityList/import.ejs.t, hygen/templates/entity/new/EntityList/use.ejs.t, hygen/templates/entity/new/EntityProperties.ejs.t, hygen/templates/entity/new/ForeignKeyGetter.ejs.t, hygen/templates/entity/new/ForeignKeyResolver.ejs.t, hygen/templates/entity/new/Form.ejs.t, hygen/templates/entity/new/SelectOptions.ejs.t, package.json
=> Low Level Hygen configuration

package.json
- sync-client -> sync-request
- Reordered packages as in 0.8.1 version
=> Modified dependencies

hygen/templates/entity/new/ForeignKeyGetter.ejs.t, hygen/templates/entity/new/ForeignKeyResolver.ejs.t, hygen/templates/entity/new/SelectOptions.ejs.t
Removed circular dependencies in entities
=> Updated hygen templates

src/entities/DefaultEntityBehavior/ListDecorator.tsx
Added date format substring in ListDecorator
=> Added isPropertyScalar date & date-time format condition

src/store/api.ts
Spread error with silenceError conditional in api.ts in post method
=> Added throw error in silenceError conditional in api post

src/components/List/List.tsx
=> Fixed itemsPerPage variable in List component

package.json, src/components/List/Content/ListContentValue.tsx, src/components/List/Content/Table/ContentTable.tsx, src/components/List/Content/hook/useParentIden.ts, src/components/List/Filter/ContentFilterSelector.tsx, src/components/List/List.tsx, src/components/List/Pagination.tsx, src/components/layout/Menu/MenuBlock.styles.tsx, src/components/layout/Menu/MenuBlock.tsx, src/services/form/Field/Autocomplete.tsx, src/services/form/FormFieldFactory.tsx, src/store/api.ts, src/store/auth.ts, src/store/menu.ts
- allow to set options order in autocomplete component
- fixed multiselect regression on lists
- resolve pagination language dynamically
- fixed double ? in list requests
- set default _page value if none
- fixed store.auth.useRefreshToken infinite loop
=> Multiple bug fixes

src/services/form/Field/Dropdown.tsx
Allow to pass choices as array of objects aparte from former key-value object
=> Array dropdown choices

.github/workflows/build.yml
Simple pipeline to build using npm 18.x
=> Add Github actions pipeline to test build

package.json, src/entities/EntityInterface.ts
=> Change FetchFksCallback type

src/services/form/Field/Autocomplete.tsx
The autocomplete with multiselect was broken since recent changes to allow array dropdown choices
=> fixed multiselect regression

src/components/List/Content/CTA/DeleteRowsButton.tsx, src/components/List/Content/Table/ContentTable.tsx
Added DeleteButton component in Actions row
=> Multi delete support

package.json, src/components/Create.tsx, src/components/Edit.tsx, src/components/List/Content/CTA/EditRowButton.tsx, src/components/List/Content/CTA/ViewRowButton.tsx, src/components/List/Content/ListContentHeader.tsx, src/components/List/Content/Shared/BuildLink.ts, src/components/List/Content/Shared/ChildEntityLinks.tsx, src/components/List/Content/hook/useParentIden.ts, src/components/List/List.tsx, src/components/layout/Breadcrumbs/Breadcrumbs.tsx, src/components/shared/useRememberedValues.tsx, src/components/withRowData.tsx, src/entities/DefaultEntityBehavior.tsx, src/hooks/useCurrentPathMatch.ts, src/hooks/useParentRow.ts, src/router/RouteContent.tsx, src/router/findRoute.tsx, src/services/entity/EntityService.ts
Added useCurrentPathMatch custom hook in replacement of useMatch
=> fixed router regressions

hygen/cy/new/Test.ejs, package.json
Cypress e2e test skeleton hygen template
=> Added hygen cypress test template

package.json, src/components/List/Content/CTA/DeleteRowButton.tsx, src/components/List/Content/CTA/DeleteRowsButton.tsx
A new delete-modal message added
=> Change Delete-Modal message

package.json, src/components/Dashboard/DashboardItemList.styles.tsx, src/components/List/Content/ListContentHeader.tsx, src/components/List/Content/Table/ContentTable.styles.tsx, src/components/List/Filter/ContentFilter.tsx, src/components/List/Filter/ContentFilterSelector.tsx, src/components/List/Filter/FilterBoxContent.styles.tsx, src/components/List/Filter/icons/FilterIconFactory.tsx, src/components/List/List.tsx, src/components/layout/Breadcrumbs/Breadcrumbs.styles.tsx, src/components/layout/Header.styles.tsx, src/components/shared/ErrorMessage.tsx, src/components/shared/InfoMessage.tsx, src/entities/DefaultEntityBehavior.styles.tsx, src/entities/DefaultEntityBehavior.tsx, src/entities/DefaultEntityBehavior/AutoForeignKeyResolver.ts, src/entities/DefaultEntityBehavior/FilterFieldsetGroups.ts, src/entities/DefaultEntityBehavior/FormField.tsx, src/entities/DefaultEntityBehavior/Unmarshaller.ts, src/entities/DefaultEntityBehavior/View.tsx, src/services/form/Field/Dropdown.styles.tsx, src/services/form/FormFieldFactory.styles.tsx, src/services/form/FormFieldFactory.tsx
- Fixed search form infinite render loop when pressing "Add and apply"
- Fixed issues related to rendering a list page with previous list row values
=> Fixed list issues

package.json, src/components/layout/Header.tsx, src/components/layout/LanguageSelector/LanguageSelector.tsx
=> Added language selector

package.json, src/components/Edit.tsx, src/components/List/Filter/FilterCriteria.tsx, src/entities/DefaultEntityBehavior/Form.tsx, src/services/entity/EntityService.ts, src/services/form/FormFieldFactory.tsx
- Enhanced initial values on edit: Use default values apart from API response
- Enhanced visual toggles and added '__default__' key: Updated algorithm to allow more complex visual toggles
- Show __null__ select option in the first position instead of the last one
=> Enhancements

package.json, src/components/List/Content/ListContentValue.tsx, src/entities/DefaultEntityBehavior/ListDecorator.tsx, src/entities/DefaultEntityBehavior/ListDecoratorMultilang.tsx, src/services/api/ParsedApiSpecInterface.ts
=> feat: multilang ScalarProperty with component

hygen/templates/cy/new/Test.ejs.t, package.json, src/services/form/Field/Autocomplete.tsx
Minor changes in order to facilitate testing
=> Enhancements for tests

package.json, src/components/layout/Header.tsx, src/components/layout/LanguageSelector/LanguageSelector.tsx, src/services/api/ApiClient.ts, src/store/i18n.ts, src/store/index.ts
Added LanguagesStore to LanguageSelector management
=> i18n store

package.json, src/components/layout/Header.tsx
header receives languages from store instead like argument
=> fix: header receives languages from store

package.json, src/components/List/Filter/FilterCriteria.tsx, src/entities/DefaultEntityBehavior/Marshaller.ts, src/services/api/ParsedApiSpecInterface.ts, src/services/entity/EntityService.ts, src/services/form/Field/Autocomplete.tsx, src/services/form/Field/Multilang.tsx, src/services/form/Field/index.ts, src/services/form/FormFieldFactory.tsx
Show a sub fieldset that wraps the languages of a property
=> Added multilang field support in forms

hygen/templates/cy/fixtures/getCollection.t, hygen/templates/cy/fixtures/getItem.t, hygen/templates/cy/fixtures/post.t, hygen/templates/cy/fixtures/put.t, hygen/templates/cy/subscreen/Test.ejs.t
Added cy fixtures and cy subscreen hygen templates
=> Enhaced hygen templates

package.json, src/components/List/Content/Table/ContentTable.styles.tsx, src/store/auth.ts
=> Token exchange store method

package.json, src/entities/DefaultEntityBehavior/Validator.ts
Added empty RegExp condition to Validator
=> Added empty RegExp condition

src/components/List/Content/ListContentValue.tsx, src/entities/DefaultEntityBehavior/AutoForeignKeyResolver.ts, src/entities/DefaultEntityBehavior/AutoSelectOptions.ts, src/entities/DefaultEntityBehavior/FormField.tsx, src/entities/DefaultEntityBehavior/ListDecorator.tsx, src/entities/DefaultEntityBehavior/Unmarshaller.ts, src/services/api/ApiSpecParser.ts, src/services/api/ParsedApiSpecInterface.ts, src/services/entity/EntityService.ts, src/services/form/FormFieldFactory.tsx
Allow to reference model subproperties in lists and forms
=> Handle embeddables

package.json, src/services/api/ParsedApiSpecInterface.ts, src/services/form/FormFieldFactory.tsx
Added new EmbeddableProperty type
=> fixed file regression

demo/src/entities/Client/Form.tsx, library/src/components/Create.tsx, library/src/components/Edit.tsx, library/src/components/ErrorBoundary.tsx, library/src/components/List/List.tsx, library/src/entities/DefaultEntityBehavior/Form/Form.tsx
Implement error boundaries (aka error handlers)
=> Error boundaries

demo/api/assets/docs.json, library/src/components/List/Filter/FilterCriteria.tsx
It was not handling properly DropdownArrayChoice select options
=> Fixed fk filters

library/package.json, library/src/components/layout/Menu/MenuBlock.tsx, library/src/store/menu.ts
menu collapsed by default & auto collapse/expansion
=> menu collapsed by default & auto collapse/expansion

demo/src/entities/Client/Form.tsx, demo/src/entities/Feature/Form.tsx, demo/src/entities/Platform/Form.tsx, demo/src/entities/Platform/Platform.tsx, demo/src/entities/User/User.tsx, demo/src/router/AppRoutes.tsx, demo/src/router/EntityMap.ts, library/src/components/List/Content/ListContentValue.tsx, library/src/store/index.ts, library/src/store/routes.ts
Remove entity links if target route doesn't exist
=> Enhanced list links

demo/src/entities/Feature/Form.tsx, demo/src/entities/Platform/Platform.tsx, demo/src/entities/User/Action/SendEmail.tsx, library/src/components/List/Content/CTA/DeleteRowButton.tsx, library/src/components/List/Content/CTA/DeleteRowsButton.tsx, library/src/components/List/List.tsx, library/src/components/shared/ConfirmDialog.styles.tsx, library/src/components/shared/ConfirmDialog.tsx, library/src/entities/EntityInterface.ts, library/src/store/list.ts
- Allow to set double check delete flag by entity
- Enhanced page reload after row deletion
=> Double check delete

demo/src/entities/Administrator/Administrator.tsx, demo/src/entities/Administrator/Form.tsx, demo/src/entities/Client/Client.tsx, demo/src/entities/Client/Form.tsx, demo/src/entities/Feature/Feature.tsx, demo/src/entities/Feature/Form.tsx, demo/src/entities/Language/Language.tsx, demo/src/entities/Platform/Form.tsx, demo/src/entities/Platform/Platform.tsx, demo/src/entities/Platform/SelectOptions.ts, demo/src/entities/User/Form.tsx, demo/src/entities/User/User.tsx, demo/src/entities/index.ts, library/src/components/Edit.tsx, library/src/components/List/Content/CTA/DeleteRowButton.tsx, library/src/components/List/List.tsx, library/src/components/View.tsx, library/src/components/shared/ConfirmDialog.styles.tsx, library/src/components/shared/ConfirmDialog.tsx, library/src/entities/DefaultEntityBehavior.tsx, library/src/entities/DefaultEntityBehavior/AutoSelectOptions.ts, library/src/entities/DefaultEntityBehavior/Marshaller.ts, library/src/entities/EntityInterface.ts
Lazy loading on foreignKeyResolver, foreignKeyGetter, selectOptions, Form and View
=> Entity partial async import

demo/src/entities/Client/Client.tsx, demo/src/entities/Language/Language.tsx, demo/src/entities/Platform/Platform.tsx, library/src/components/List/Content/ListContent.scoped.scss, library/src/components/List/Content/ListContentValue.tsx, library/src/components/List/Content/Table/ContentTable.scoped.scss, library/src/components/List/Content/Table/ContentTable.styles.tsx, library/src/components/List/Content/Table/ContentTable.tsx, library/src/components/List/Content/Table/ContentTableColumn.tsx, library/src/components/List/Content/Table/ContentTableHead/ContentTableHead.tsx, library/src/components/Login/Login.scoped.scss, library/src/components/Login/Login.styles.tsx, library/src/components/Login/Login.tsx, library/src/sass/components/_link.scss, library/src/sass/layout/_sidemenu.scss
add percentage width to table columns
=> Content table style adjustments

library/src/services/api/genericForeigKeyResolver.ts
Removed condition where it sets to empty foreign key fields
=> Removed condition where it sets to empty foreign key fields

library/src/components/List/Content/CTA/DeleteRowButton.tsx, library/src/components/layout/Header/Settings/Settings.tsx, library/src/translations/ca.json, library/src/translations/en.json, library/src/translations/es.json, library/src/translations/it.json
Added settings and generic deletion translations
=> Added missing translations

library/src/services/form/Field/TextField/TextField.styles.tsx
- Added styles to increase height of multiline text fields
=> Added styles when multiline textField

library/package.json, library/src/components/Create.tsx, library/src/entities/DefaultEntityBehavior/Form/Form.tsx, library/src/translations/ca.json, library/src/translations/en.json, library/src/translations/es.json, library/src/translations/it.json
Support create pages that have no list to return to
=> Added "create only" screen support

demo/src/entities/Feature/Feature.tsx, library/src/entities/DefaultEntityBehavior/Validator.ts, library/src/services/form/Field/Multilang.tsx
Allow to set unset required flag on multilang fields
=> fixed required property application on multilang fields

demo/src/i18n.js, library/package.json, yarn.lock
Some translation issues have been reported recently:
- https://github.com/irontec/ivozprovider/issues/2534
- https://github.com/irontec/ivozprovider/issues/2422
We suspect it's related to the browser language. This PR aims to address that issue.
=> Use fallback lang if browser language has no translations

demo/src/entities/Client/Client.tsx, demo/src/entities/Client/Form.tsx, demo/src/entities/Client/View.tsx, demo/src/entities/Platform/Form.tsx, demo/src/entities/Platform/View.tsx, demo/src/entities/User/Form.tsx, demo/src/i18n.js, demo/src/router/EntityMap.ts, demo/src/router/addCustomRoutes.ts, library/package.json, library/src/components/Detail.tsx, library/src/entities/DefaultEntityBehavior/Form/Form.tsx, library/src/entities/DefaultEntityBehavior/View.tsx, library/src/entities/EntityInterface.ts, library/src/entities/data/useFkChoices.tsx
Call useFkChoices automatically if no fkChoices was provided in edit and detail components
=> Simplified fk choices

library/package.json, library/src/components/Detail.tsx, library/src/entities/DefaultEntityBehavior/View.tsx, library/src/entities/EntityInterface.ts
Ensure row data is formik compatible
=> Use unmarshaller in detail views

library/package.json, library/src/components/List/List.tsx, library/src/components/List/useEncodedQueryStringParams.tsx
It's broken with special characters like `+`
=> Escape search arguments

library/package.json, library/src/components/List/Filter/ContentFilterSelector/ContentFilterRow.tsx, library/src/components/List/Filter/ContentFilterSelector/ContentFilterSelector.styles.tsx, library/src/entities/DefaultEntityBehavior/ListDecorator.tsx
Updated datetime representation in lists as well for consistency
=> Added datetime-local UI helper in the search form

library/package.json, library/src/components/List/Content/FastSearchField.tsx, library/src/services/form/Field/TextField/TextField.tsx
Enhanced how fast search is triggered
- Doubled submit countdown
- Submit on press enter
- Disabled submit countdown on datetimes
- Trigger on blur only for datetimes
=> Datetime fast search enhancements

library/package.json, library/src/components/List/Content/Shared/ChildEntityLinks.tsx
Extract entity icon into list if there is only one item
=> Added Slice condition for single elements on more menu item

library/package.json, library/src/components/List/Content/Shared/ChildEntityLinks.tsx, library/src/services/form/Field/FileUploader/FileUploader.styles.tsx, library/src/services/form/Field/FileUploader/Variant/ImageFileUploader.tsx
Allow image preview when downloadPath exists
=> Allow image preview

library/package.json, library/src/components/List/Content/Table/ContentTable.styles.tsx
Fixed more menu item links to fit the entire box
=> Added 100% width to more menu item links

library/.eslintrc.json, library/package.json, library/src/services/form/Field/FileUploader/FileUploader.styles.tsx, library/src/services/form/Field/FileUploader/FileUploader.tsx, library/src/services/form/Field/FileUploader/Variant/ImageFileUploader.tsx, library/src/services/form/Field/TextField/TextField.styles.tsx
Added remove file button When property is not required in props
=> Added remove file button

library/package.json, library/src/services/form/Field/TextField/TextField.tsx
Replaces this incorrectly named PR:
https://github.com/irontec/ivoz-ui/pull/130
=> Fixed datetime pickers

library/src/services/form/Field/Autocomplete/Autocomplete.tsx
Added support for __auto__ default value
=> Fixed error when id equals zero
